<?php
declare(strict_types=1);

// Letscount SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

LetscountUtility::setRegistrar(function (LetscountUtility $u): void {
    $u->clean = [LetscountClean::class, 'call'];
    $u->done = [LetscountDone::class, 'call'];
    $u->make_error = [LetscountMakeError::class, 'call'];
    $u->feature_add = [LetscountFeatureAdd::class, 'call'];
    $u->feature_hook = [LetscountFeatureHook::class, 'call'];
    $u->feature_init = [LetscountFeatureInit::class, 'call'];
    $u->fetcher = [LetscountFetcher::class, 'call'];
    $u->make_fetch_def = [LetscountMakeFetchDef::class, 'call'];
    $u->make_context = [LetscountMakeContext::class, 'call'];
    $u->make_options = [LetscountMakeOptions::class, 'call'];
    $u->make_request = [LetscountMakeRequest::class, 'call'];
    $u->make_response = [LetscountMakeResponse::class, 'call'];
    $u->make_result = [LetscountMakeResult::class, 'call'];
    $u->make_point = [LetscountMakePoint::class, 'call'];
    $u->make_spec = [LetscountMakeSpec::class, 'call'];
    $u->make_url = [LetscountMakeUrl::class, 'call'];
    $u->param = [LetscountParam::class, 'call'];
    $u->prepare_auth = [LetscountPrepareAuth::class, 'call'];
    $u->prepare_body = [LetscountPrepareBody::class, 'call'];
    $u->prepare_headers = [LetscountPrepareHeaders::class, 'call'];
    $u->prepare_method = [LetscountPrepareMethod::class, 'call'];
    $u->prepare_params = [LetscountPrepareParams::class, 'call'];
    $u->prepare_path = [LetscountPreparePath::class, 'call'];
    $u->prepare_query = [LetscountPrepareQuery::class, 'call'];
    $u->graphql_body = [LetscountGraphql::class, 'body'];
    $u->graphql_errors = [LetscountGraphql::class, 'errors'];
    $u->result_basic = [LetscountResultBasic::class, 'call'];
    $u->result_body = [LetscountResultBody::class, 'call'];
    $u->result_headers = [LetscountResultHeaders::class, 'call'];
    $u->transform_request = [LetscountTransformRequest::class, 'call'];
    $u->transform_response = [LetscountTransformResponse::class, 'call'];
});
